-- One comprehensive lesson-note ("konu anlatimi") per writing type,
-- written from scratch for Pasific to match the writing_type_guides schema.

insert into writing_type_guides (writing_type_id, title, summary, content, key_phrases)
values
  ('opinion_essay', 'How to Write an Opinion Essay', 'State a clear personal opinion and support it with well-developed reasons, addressing the other side before concluding.', 'An opinion essay asks you to argue for a personal point of view on a given topic. The examiner wants to see a clear position, developed reasoning and controlled language — not just a list of ideas.

Structure: start with a short introduction that restates the question in your own words and gives your opinion in one clear sentence (your thesis). The body usually has two or three paragraphs, each built around one main reason, developed with an explanation and, ideally, a specific example. A strong opinion essay also includes a paragraph that acknowledges an opposing view before explaining why you still hold your position — this shows maturity of thought rather than a one-sided rant. The conclusion restates your opinion and adds a final thought; it should not simply repeat the introduction word for word.

Language: use opinion phrases naturally (In my view, I would argue that, It seems to me that) rather than repeating ''I think'' every paragraph. Use linking words to organise reasons (Firstly, Moreover, In addition) and to introduce the counter-argument (Admittedly, Some people argue that, however). Avoid absolute claims (''everyone agrees'') unless you can support them.

Common mistakes: giving an opinion without reasons, listing reasons without developing any of them, ignoring the counter-argument completely, or drifting into a different topic to fill word count. Read your final paragraph and check it actually answers the exact question asked.', array['In my view / In my opinion','I would argue that...','It seems to me that...','Admittedly, ... / Some people argue that..., however','On balance, I believe that...','This is not to say that... but rather...']),
  ('argumentative_essay', 'How to Write an Argumentative Essay', 'Build a persuasive, well-evidenced case for a position, directly engaging with and rebutting the strongest opposing arguments.', 'An argumentative essay is more assertive than a simple opinion essay: you are not just sharing a view, you are trying to persuade the reader that your position is correct, using logic and evidence rather than personal preference alone.

Structure: the introduction should frame the debate and state your position confidently. Each body paragraph should present one argument, supported by reasoning, and ideally a fact, statistic or specific example rather than a vague generalisation. A genuinely strong argumentative essay contains at least one paragraph that takes the opposing view seriously and then rebuts it with logic, not just dismisses it — this rebuttal is often what separates a good essay from an excellent one. The conclusion should reaffirm your position with a sense of conviction, sometimes adding a call to action or a final consequence if the reader doesn''t accept your view.

Language: use assertive but reasoned language (It is clear that, The evidence suggests, This argument fails to consider) rather than emotional or exaggerated language. Use logical connectors precisely: therefore, consequently, this implies that, given that. When rebutting, use concession-then-rebuttal structures: ''While it is true that X, this overlooks Y.''

Common mistakes: asserting a claim without any supporting reasoning (''this is obviously true''), presenting only your side without engaging the opposition at all, or being so aggressive in tone that the argument feels one-sided and unconvincing rather than persuasive.', array['It is clear that...','The evidence suggests that...','While it is true that X, this overlooks Y','This argument fails to consider...','Consequently, ... / Given that...','On balance, the case for/against ... is stronger']),
  ('for_and_against_essay', 'How to Write a For and Against Essay', 'Present balanced arguments on both sides of an issue with a neutral tone, saving your personal opinion for the conclusion only.', 'A for-and-against essay is different from an opinion or argumentative essay: your job is to present both sides of a debate fairly and objectively, without revealing your own opinion until the very end (if at all).

Structure: the introduction presents the topic neutrally, without taking a side. The next paragraph presents arguments in favour of the topic (at least two, briefly developed), and the following paragraph presents arguments against it, with roughly equal space and development. Keep the tone balanced — do not let one side sound stronger through word choice alone. Only in the conclusion should you add your own view, if the task asks for it, clearly separated from the neutral body paragraphs.

Language: this genre relies heavily on balancing and contrast language. Use ''On the one hand... on the other hand'', ''Proponents argue that... however, critics claim that...'', and neutral reporting verbs (some argue, it is claimed, many believe) rather than first-person opinion verbs in the body. Save ''I believe'' or ''In my opinion'' for the conclusion only.

Common mistakes: accidentally giving your opinion in the body paragraphs (revealing bias too early), giving one side much more development than the other, or forgetting the concluding personal opinion when the task specifically asks for one.', array['On the one hand... on the other hand...','Proponents argue that... / Critics claim that...','It is often said that...','Weighing up both sides,...','Having considered both arguments, I believe...','There are, however, drawbacks to this view']),
  ('advantages_disadvantages_essay', 'How to Write an Advantages and Disadvantages Essay', 'List and develop clear advantages and disadvantages of a topic in separate, balanced sections, then reach a supported conclusion.', 'This essay type asks you to weigh the pros and cons of a topic (a technology, a policy, a lifestyle choice) rather than argue for one fixed position from the start.

Structure: introduce the topic neutrally. Devote one paragraph clearly to advantages (usually two, each explained with a brief example) and a separate paragraph clearly to disadvantages, again developed rather than just listed. Keep the two sections genuinely separate — mixing advantages and disadvantages within the same paragraph makes the essay hard to follow. The conclusion should weigh the two sides against each other and give a final judgement (which side is stronger, or under what conditions one might outweigh the other), rather than simply restating both lists.

Language: use clear signalling words to separate the sections (One major advantage is..., A further benefit is..., On the negative side..., A significant drawback is...). In the conclusion, use weighing language: ''While there are clear benefits, the drawbacks are, on balance, more significant because...'' or ''The advantages appear to outweigh the disadvantages, particularly when...''.

Common mistakes: giving three advantages and only one disadvantage (imbalanced development), listing points without explaining why they matter, or writing a conclusion that just repeats the lists instead of genuinely weighing them.', array['One major advantage is...','A further benefit is...','On the negative side, ... / A significant drawback is...','While there are clear benefits, ...','The advantages appear to outweigh the disadvantages because...','This depends largely on...']),
  ('problem_solution_essay', 'How to Write a Problem-Solution Essay', 'Clearly identify the causes of a real problem, then propose specific, realistic solutions that directly address each cause.', 'A problem-solution essay analyses a real issue and proposes practical ways to fix it. The examiner is looking for a clear link between the problems you identify and the solutions you propose — solutions that don''t match the stated problems will lose marks even if they''re well written.

Structure: the introduction states the problem and its significance briefly. The next section (one or two paragraphs) explains the main causes or aspects of the problem with specific, credible detail — avoid vague statements like ''this is a big problem''; explain why and how. The following section proposes solutions, ideally one solution per cause discussed, explained with enough detail to show it''s realistic (who would do it, how it would work). The conclusion evaluates the overall feasibility — are these solutions likely to work, and what would it take to implement them?

Language: use cause-and-effect language for the problem section (this is largely due to, this stems from, as a result of) and suggestion language for solutions (one way to address this would be, a more effective approach might be, this could be tackled by). At higher levels, hedge appropriately: ''this alone would not solve the problem, but combined with X, it could meaningfully reduce it.''

Common mistakes: proposing generic solutions that don''t connect to the specific causes described, listing solutions without explaining how they would actually work, or spending so much time on the problem that there''s no room to develop the solutions properly.', array['This is largely due to... / This stems from...','One way to address this would be...','A more effective approach might be...','This could be tackled by...','While this would help, it would not fully solve...','A combination of these measures could...']),
  ('cause_effect_essay', 'How to Write a Cause and Effect Essay', 'Explain the specific causes behind a phenomenon and trace their logical effects, keeping the two clearly and consistently separated.', 'A cause-and-effect essay explains why something happens (causes) and what happens as a result (effects). Unlike a problem-solution essay, it does not need to propose fixes — its job is analytical, not corrective.

Structure: the introduction identifies the phenomenon you''ll analyse. You can organise the body in two ways: either all causes first, then all effects (block structure), or cause-effect pairs one after another (chain structure) — either is acceptable if the logic is clear. Each cause should be developed with specific reasoning, not just named. Effects should be logically connected to the causes already discussed, and at higher levels, distinguishing between short-term and long-term effects shows more sophisticated thinking. The conclusion can reflect on the overall significance of the pattern you''ve described.

Language: causes need cause-language (this is driven by, one factor behind this is, this can be attributed to) and effects need effect-language (as a consequence, this results in, this has led to). Avoid mixing them up — a common error is describing a cause using effect language or vice versa. Sequencing words (firstly, subsequently, in turn) help show how one effect can itself become the cause of the next.

Common mistakes: listing causes and effects without clearly linking which effect comes from which cause, confusing correlation with causation (assuming one thing causes another just because they happen together), or repeating the same idea as both a cause and an effect.', array['This is driven by... / One factor behind this is...','This can be attributed to...','As a consequence, ... / This has led to...','In turn, this results in...','A further, longer-term effect is...','This pattern reflects a broader shift in...']),
  ('compare_contrast_essay', 'How to Write a Compare and Contrast Essay', 'Compare two options using consistent, explicit criteria, then reach a conclusion about their relative merits or suitability.', 'A compare-and-contrast essay examines the similarities and/or differences between two things — two places, two approaches, two products — using consistent criteria rather than a random list of observations.

Structure: decide early whether you''ll use a block structure (everything about option A, then everything about option B) or a point-by-point structure (compare both options on criterion 1, then criterion 2, then criterion 3). Point-by-point is usually easier for the reader to follow and is generally preferred at higher levels. Choose 2-3 clear criteria (cost, convenience, effectiveness, suitability for different users) and apply them consistently to both options. The conclusion should go beyond just summarising — ideally it reaches a genuine judgement (which is better overall, or in which situations each is better suited) rather than a flat ''both have pros and cons''.

Language: comparison needs both similarity language (similarly, likewise, in the same way) and contrast language (whereas, in contrast, on the other hand, unlike X, Y...). Comparative and superlative structures are useful (more/less... than, the most significant difference is). At higher levels, hedge nuanced conclusions: ''X is generally preferable, although Y may suit those who prioritise...''.

Common mistakes: comparing on different criteria for each option (making the comparison uneven), simply describing both options separately without ever directly comparing them, or reaching a conclusion that doesn''t follow from the comparison actually made in the body.', array['Similarly, ... / Likewise, ...','Whereas... / In contrast, ...','Unlike X, Y...','The most significant difference is...','X is generally preferable, although...','Ultimately, the better choice depends on...']),
  ('formal_email', 'How to Write a Formal Email', 'Use a consistently formal register from greeting to sign-off, state your purpose clearly and early, and keep requests specific.', 'A formal email is written to someone you don''t know well or in a professional/institutional context — a school, a company, an official body. Register consistency matters more than in almost any other genre: one informal word can undermine an otherwise well-written email.

Structure: open with an appropriate formal greeting (Dear Sir or Madam if the name is unknown; Dear Mr/Ms [Surname] if known). State your purpose for writing in the first or second sentence — don''t make the reader guess. Develop your request or information in short, focused paragraphs, one idea per paragraph. Close with a polite, appropriately formal closing line (I look forward to hearing from you) and match your sign-off to your greeting: ''Yours faithfully'' if you used ''Dear Sir or Madam'', ''Yours sincerely'' if you used a named greeting.

Language: avoid contractions (don''t → do not), phrasal verbs where a more formal single word exists (find out → determine, get back to → respond to), and any slang. Use polite, indirect request forms (I would be grateful if you could..., Would it be possible to...) rather than direct commands (Send me...). Keep sentences clear and not overly long — formal does not mean complicated.

Common mistakes: mismatching the greeting and sign-off, slipping into informal vocabulary or contractions partway through, or being too vague about what you actually want the reader to do.', array['I am writing to enquire about / to inform you that...','I would be grateful if you could...','Would it be possible to...?','Please do not hesitate to contact me if...','I look forward to hearing from you.','Yours faithfully, / Yours sincerely,']),
  ('informal_email', 'How to Write an Informal Email', 'Write in a natural, friendly voice as if speaking to a close friend, using contractions and everyday vocabulary throughout.', 'An informal email is written to a friend or family member. The examiner is checking whether you can write naturally and appropriately casually — a formal-sounding ''informal'' email is actually a common way candidates lose marks in this genre.

Structure: open with a casual greeting (Hi [name], Hey [name]) and often a friendly opening line asking how the person is or referring to their last message. Organise the body loosely around your main news or purpose — informal emails don''t need the rigid one-idea-per-paragraph structure of formal writing, but should still be easy to follow. Close with a casual sign-off (Take care, Speak soon, Love/Best) matched to how well you know the person.

Language: use contractions naturally (I''m, don''t, we''ve), everyday vocabulary, and conversational discourse markers (Anyway, By the way, Guess what). Exclamation marks and informal punctuation are acceptable in moderation. Ask the reader questions to keep the tone genuinely conversational, as you would in a real message to a friend.

Common mistakes: writing in an accidentally formal register (full sentences, no contractions, ''Dear'' greetings), being too generic instead of sounding like a real message to a specific person, or forgetting to actually respond to or ask about the other person if the task implies a two-way exchange.', array['Hi [name]! / Hey [name]!','How are you? / Hope you''re doing well!','Anyway, ... / By the way, ...','Guess what — ...!','Let me know what you think!','Take care, / Speak soon,']),
  ('complaint_letter', 'How to Write a Complaint Letter', 'Describe the problem clearly and factually, then state a specific, reasonable request — firm in tone, but never aggressive.', 'A complaint letter formally reports a problem with a product or service and requests a specific resolution. The tone needs to be firm and clear without becoming rude — an overly aggressive letter is actually less persuasive and less appropriate for the genre.

Structure: open formally, stating what you are writing about and any relevant reference details (order number, date, location). Describe what happened factually and in a logical order (chronological is usually clearest) — stick to what actually happened rather than exaggerating. Explain the impact this had on you briefly. State clearly what you want the company to do about it (a refund, a replacement, an apology, an explanation) — vague complaints without a specific request are weaker. Close formally, often with a reasonable deadline or expectation for response.

Language: use firm but professional language (I was extremely disappointed to find that, I am writing to express my dissatisfaction with) rather than emotional or insulting language. Passive voice is often useful for describing what went wrong without sounding overly accusatory (''the item was found to be faulty'' rather than ''you sent me a broken item''). Be specific and factual rather than using vague exaggeration (''the worst service I have ever experienced'').

Common mistakes: describing the problem but never stating what you actually want done about it, using aggressive or insulting language that undermines your credibility, or failing to include specific details (dates, order numbers) that would make the complaint actionable.', array['I am writing to express my dissatisfaction with...','I was extremely disappointed to find that...','This is not the standard of service I would expect...','I would like to request a full refund / replacement.','I trust this matter will be resolved promptly.','I look forward to your response.']),
  ('application_letter', 'How to Write an Application Letter', 'Present specific, relevant evidence of your suitability, connected clearly to what the opportunity is actually looking for.', 'An application letter is written to apply for something — a job, a volunteer role, a place on a programme. The key skill being tested is your ability to present yourself persuasively using specific, relevant evidence rather than generic self-praise.

Structure: open by stating clearly what you are applying for and where you saw it advertised (if relevant). The main body should present your relevant qualifications, experience or qualities — ideally connected explicitly to what the specific opportunity requires, not just a generic list of good qualities. Explain your motivation genuinely: why this opportunity, specifically, rather than a generic ''I have always wanted to...''. Close by stating your availability and inviting further contact (an interview, more information), and thank the reader for considering your application.

Language: use confident but not arrogant language (I have developed strong skills in..., I believe my experience in X would allow me to...) and formal register throughout, similar to a formal email/letter. Be specific: ''I organised a fundraising event that raised £500'' is far more persuasive than ''I am a hard-working person.''

Common mistakes: making only generic claims about your qualities without specific evidence, failing to connect your background to what THIS particular opportunity needs, or forgetting to state your availability or next steps clearly.', array['I am writing to apply for...','I have developed strong skills in...','I believe my experience in X would allow me to...','I am available for interview at your convenience.','I would welcome the opportunity to discuss...','Thank you for considering my application.']),
  ('article', 'How to Write an Article', 'Write in an engaging, reader-friendly voice with a catchy title, addressing the reader directly and building towards a clear takeaway.', 'An article is written for a magazine, website or newsletter, aimed at engaging a general reader — this is a much more stylistically free genre than a report or formal letter, and examiners reward genuine voice and engagement, not just correctness.

Structure: start with a catchy, relevant title that hints at the content. The opening should hook the reader — a question, a surprising fact, or a vivid scene often work better than a plain statement of topic. The body should develop your ideas in an engaging order, often building towards a main point or insight rather than just listing facts. A strong closing line leaves the reader with something memorable — a reflection, a recommendation, or a thought-provoking final sentence — rather than a flat summary.

Language: this genre allows (and rewards) a more varied, lively register than formal writing: rhetorical questions, direct address to the reader (you might be wondering...), varied sentence lengths including short sentences for effect, and vivid, precise vocabulary. Humour or a personal anecdote, where appropriate, can strengthen engagement.

Common mistakes: writing in an overly formal, report-like register that doesn''t suit the genre, having a flat or generic title, or ending with a bland summary instead of a genuinely memorable final thought.', array['Have you ever wondered...?','It turns out that...','Picture this: ...','Whatever the reason, one thing is clear:...','So, what does this mean for...?','In short, ...']),
  ('report', 'How to Write a Report', 'Use clear headings to separate findings from recommendations, and keep the tone objective, factual and evidence-based throughout.', 'A report presents information (often from a survey, an investigation or an evaluation) to a specific reader — a manager, a head teacher, a committee — who will use it to make a decision. Clarity and objectivity matter more than style here.

Structure: use clear headings (Introduction, Findings, Recommendations, Conclusion are typical) so the reader can scan the report quickly. The introduction states the report''s purpose in one or two sentences. The findings section presents what you discovered, organised logically (by theme, by importance, or by respondent group), using specific supporting detail (numbers, percentages, direct feedback) rather than vague generalisations. The recommendations section should follow directly and logically from the findings — each recommendation should clearly address a finding already discussed. A brief conclusion can summarise the overall picture.

Language: keep the tone objective and impersonal (It was found that, Respondents indicated that, It is recommended that) rather than personal opinion (''I think we should...''). Passive voice is common and appropriate in this genre. Use precise, factual vocabulary and avoid emotive or exaggerated language.

Common mistakes: writing in flowing prose without headings (making the report hard to scan), giving recommendations that don''t connect to any finding presented, or slipping into a personal, opinion-essay style tone instead of an objective report register.', array['The purpose of this report is to...','It was found that... / Respondents indicated that...','A recurring theme was...','It is recommended that...','This would likely result in...','In conclusion, the findings suggest that...']),
  ('review', 'How to Write a Review', 'Give a balanced, specific evaluation with concrete evidence for your judgements, ending with clear guidance for the reader.', 'A review evaluates something — a film, book, restaurant, product, event — for a reader deciding whether to try it themselves. The key skill is critical evaluation, not just description: a review that only summarises the plot or lists the menu without judging it is not doing its job.

Structure: a short opening identifies what you''re reviewing and gives a general impression. The body should evaluate specific aspects (for a film: plot, acting, style; for a restaurant: food, service, atmosphere), giving both strengths and weaknesses where genuinely relevant — a review that is only positive or only negative is usually less convincing and less useful. Each judgement should be backed with specific evidence, not vague praise or criticism (''the acting felt flat, particularly in the courtroom scenes'' rather than ''the acting was bad''). The conclusion should give clear guidance: would you recommend it, and to whom specifically?

Language: use evaluative vocabulary precisely (compelling, underwhelming, well-paced, overpriced) rather than generic words (good, bad, nice). A confident, distinctive critical voice is rewarded at higher levels — reviews are one of the few genres where personality in writing style is genuinely an asset.

Common mistakes: only summarising/describing without actually evaluating, giving vague judgements without supporting evidence, or failing to give clear guidance about who would or wouldn''t enjoy it.', array['Overall, I found this to be...','What stood out most was...','On the downside, ...','This won''t appeal to everyone, but...','I would (not) recommend this to...','Rating: [x] out of 5']),
  ('narrative_story', 'How to Write a Narrative Story', 'Tell a story with a clear arc — a build-up, a turning point and a resolution — using vivid, well-paced descriptive language.', 'A narrative story tells a real or invented sequence of events, usually built around a clear turning point or key moment rather than a flat list of things that happened one after another.

Structure: an effective story has a shape — a beginning that sets the scene, a build-up of tension or interest, a key turning point or climax, and a resolution or reflection at the end. Avoid simply narrating events in order without any sense of build-up (''and then... and then... and then''); instead, decide what the key moment of your story is and structure everything around it. At higher levels, techniques like starting mid-action, a brief flashback, or non-linear structure can create a more sophisticated effect, but should be used with control, not just for novelty.

Language: use past tenses accurately and consistently (past simple for main events, past continuous for background action, past perfect for events before the main timeline). Use vivid, specific vocabulary and varied sentence lengths — short sentences can create tension or impact; longer sentences can build atmosphere. Show emotions through detail and action rather than simply stating them (''her hands were shaking as she reached for the phone'' rather than ''she was scared'').

Common mistakes: a flat, listy sequence of events with no real turning point, inconsistent or inaccurate tense use, or explaining emotions directly instead of showing them through detail and action.', array['It was [time/place] when...','Little did I know that...','Without warning, ...','My heart was racing as...','Looking back now, ...','It was only later that I realised...']),
  ('descriptive_writing', 'How to Write Descriptive Writing', 'Use precise, varied sensory detail organised in a clear order to create a vivid, coherent picture or atmosphere for the reader.', 'Descriptive writing creates a vivid picture of a place, person, object or scene for the reader, using precise sensory detail rather than a simple list of adjectives.

Structure: organise your description with a clear logical order — spatially (near to far, top to bottom), by importance (most striking feature first), or by sense (sight, then sound, then smell) — so the reader can follow the scene rather than jumping randomly between details. Aim to include more than one sense: sight alone gives a flat description, while sound, smell, touch and even taste create a fuller, more immersive picture. At higher levels, description can build towards a mood or atmosphere, and even a closing reflection connecting the physical scene to a feeling or meaning.

Language: use precise, specific vocabulary rather than generic adjectives (''a bustling, narrow street lined with striped awnings'' rather than ''a nice street''). Figurative language (similes, metaphors) can add vividness when used with control — but overusing it can feel forced. Varied sentence structure (some long, flowing sentences; some short, sharp ones) helps control pacing and emphasis.

Common mistakes: relying only on sight and generic adjectives, listing details with no organising order, or overusing figurative language until the writing feels overwrought rather than vivid.', array['The air was thick with...','A faint smell of ... drifted through...','In the distance, ...','Everywhere you looked, ...','There was something about the way...','It was the kind of place where...']),
  ('blog_post', 'How to Write a Blog Post', 'Write in a natural, personal voice with a clear organising structure, sharing honest reflection rather than only generic conclusions.', 'A blog post shares personal experience, opinion or advice with an online readership. It sits between an article and an informal email in register: personal and conversational, but usually a little more structured than a message to a friend.

Structure: an engaging title and opening hook draw the reader in — a direct question, a surprising admission, or a relatable scenario often work well. The body is often organised around a clear structure (a numbered list, a chronological account, a few key lessons) that makes the post easy to follow and share. The best blog posts go beyond generic conclusions (''it taught me to work hard'') into something more specific and honest, reflecting genuinely on what the experience revealed. A warm, direct closing (often inviting engagement) suits the genre well.

Language: use a natural, first-person, conversational voice — contractions, direct address to the reader (you might be thinking...), and rhetorical questions are all appropriate. Honesty and specificity are valued over neatness: a blog post that acknowledges genuine difficulty or nuance, rather than only listing generic positives, tends to feel more authentic and engaging.

Common mistakes: writing in an overly formal register that doesn''t suit the personal genre, ending with a generic ''lesson learned'' rather than a specific, honest reflection, or organising the post so loosely that it''s hard to follow.', array['Here''s what I learned...','You might be thinking...','Looking back, I realise that...','It wasn''t all easy, though.','If there''s one thing I''d tell my past self, it''s...','What about you — have you ever...?'])
on conflict (writing_type_id) do update set
  title = excluded.title, summary = excluded.summary, content = excluded.content, key_phrases = excluded.key_phrases, updated_at = now();